### ISSUE TITLE
Error: `signature not match`.

### ISSUE THREAD

**Issue by svex99** [BingX-API/BingX-swap-api-doc#11]
I'm trying to make a request to the `/api/v1/user/getBalance` endpoint of the API as [explained in the documentation](https://bingx-api.github.io/docs/swap/authentication.html#generate-an-api-key). But I get constantly `{"code":80014,"msg":"signature not match","data":{}}`.

I tried [Python](https://github.com/BingX-API/BingX-swap-api-doc/blob/master/demo/py3/trade_demo.py) and [Go](https://github.com/BingX-API/BingX-swap-api-doc/blob/master/demo/go/trade_demo.go) demos, but still the same result.

I **triple** checked the API key and API secret.

Currently, using Python 3.9.5 and Go 1.18.1.

UPDATE: Same error with Postman collection.

Thanks in advance!

**Comment by lyenliang** [comment]
I have the same problem.

**Comment by vndkubi** [comment]
Me too. I have same problem

**Comment by mjreich** [comment]
same

**Comment by impromptus4** [comment]
Same problem in java

**Comment by lyenliang** [comment]
This problem has been solved by BingX.

Now the return value becomes something like this:

```
getBalance: b'{"code":0,"msg":"","ttl":1,"data":{"account":{"userId":"123456789123456789","currency":"USDT","balance":0,"equity":0,"unrealisedPNL":0,"realisedPNL":0,"availableMargin":0,"usedMargin":0,"freezedMargin":0,"longLeverage":5,"shortLeverage":5}}}'
```
