### ISSUE TITLE
Websocket keeps disconnecting

### ISSUE THREAD

**Issue by hirbod-codes** [BingX-API/BingX-swap-api-doc#25]
hi i'm using .net to subscribe in kline market data and after receiving couple of candles server suddenly disconnects

Exception message: The remote party closed the WebSocket connection without completing the close handshake.

here's the code

```c#
class BingxWsCandle
{
    public string c { get; set; } = null!;
    public string o { get; set; } = null!;
    public string h { get; set; } = null!;
    public string l { get; set; } = null!;
    public string v { get; set; } = null!;
    public long T { get; set; }
}

class WsResponse
{
    public string Id { get; set; } = null!;
    public int Code { get; set; }
    public string? S { get; set; } = null!;
    public string? DataType { get; set; } = null!;
    public BingxWsCandle[]? Data { get; set; } = null!;
}
async Task websocket()
{
    ClientWebSocket ws = new();
  
    await ws.ConnectAsync(new Uri("wss://open-api-swap.bingx.com/swap-market"), CancellationToken.None);
    
    string id = Guid.NewGuid().ToString();
    while (true)
    {
        if (ws.State != WebSocketState.Open)
            continue;
    
        await ws.SendAsync(new ArraySegment<byte>(Encoding.UTF8.GetBytes(JsonSerializer.Serialize(new
        {
            id,
            reqType = "sub",
            dataType = $"{Symbol}@kline_{GetStringTimeFrame(timeFrame)}"
        }))), WebSocketMessageType.Text, true, CancellationToken.None);
    
        break;
    }
    
    while (true)
    {
        if (ws.State == WebSocketState.None || ws.State == WebSocketState.Connecting)
            continue;
    
        if (ws.State == WebSocketState.Closed || ws.State == WebSocketState.Aborted || ws.State == WebSocketState.CloseReceived)
        {
            _logger.Information("Websocket state: {state}", ws.State);
            break;
        }
    
        byte[] buffer = new byte[1024 * 4];
        WebSocketReceiveResult result = await ws.ReceiveAsync(new ArraySegment<byte>(buffer), CancellationToken.None);
    
        if (result.MessageType == WebSocketMessageType.Close)
        {
            string? m = null;
            try
            {
                byte[] b = await _utilities.DecompressBytes(buffer);
    
                m = Encoding.UTF8.GetString(await _utilities.DecompressBytes(buffer), 0, b.Length);
            }
            catch (System.Exception) { }
    
            _logger.Warning("A close message was received by the broker, restarting...");
    
            if (m != null)
                _logger.Debug("message: {@message}", m);
    
            await Task.Delay(10 * 1000);
    
            throw new WebSocketClosedByBrokerException();
        }
    
        byte[] bytes = await _utilities.DecompressBytes(buffer);
    
        string message = Encoding.UTF8.GetString(bytes, 0, bytes.Length);
    
        if (message == "Ping")
        {
            _logger.Verbose(message);
    
            await ws.SendAsync(new ArraySegment<byte>(Encoding.UTF8.GetBytes("Pong")), WebSocketMessageType.Binary, true, CancellationToken.None);
            buffer = new byte[1024 * 4];
            continue;
        }
    
        BingxWsResponse? wsResponse = JsonSerializer.Deserialize<BingxWsResponse>(message, new JsonSerializerOptions(JsonSerializerDefaults.Web));
    
        if (wsResponse != null && wsResponse.Id != null && wsResponse.Id != id)
            throw new BingxException("Invalid id provided by the server.");
    
        if (wsResponse == null || wsResponse.Data == null || !wsResponse.Data.Any())
        {
            _logger.Warning("No data provided by the broker, skipping...");
            continue;
        }
    }
    
    await ws.CloseAsync(WebSocketCloseStatus.Empty, null, CancellationToken.None);
    
    _logger.Information("Finished listening for candles...");
}
// code
```

i ran the while loop 50 times to just to test things out.

**Comment by hirbod-codes** [comment]
sorry i was not checking the State property (WebSocketState).

**Comment by bingx-support** [comment]
@hirbod-codes hi for restful api in VST  can use this api 
https://bingx-api.github.io/docs/#/en-us/swapV2/trade-api.html#Trade%20order%20in%20demo%20trading

for websocket ， currently not support VST yet

**Comment by hirbod-codes** [comment]
it seems that remote party is closing web socket connection after couple of days, is there any reason?

**Comment by hirbod-codes** [comment]
Is there any policy about limiting the duration a web socket connection is open? or the number of web socket connections per IP, per API key, or does it depend on the time frame? (I'm talking about web socket for kline data, not account data).
I mean can I have couple of kline web socket connections open, in different timeframes, in one symbol, with one account API key?

or may be it's just network packet loss?!
please clarify.

**Comment by bingx-support** [comment]
Hello,
We suggest that you only subscribe to the dataType you actually need.

> From: "Hirbod ***@***.***>
> Date:  Thu, Apr 18, 2024, 02:16
> Subject:  Re: [BingX-API/BingX-swap-api-doc] Websocket keeps disconnecting (Issue #25)
> To: ***@***.***>
> Cc: ***@***.***>, ***@***.***>
> Is there any policy about limiting the duration a web socket connection is open? or the number of web socket connections per IP, per API key, or does it depend on the time frame? (I'm talking about web socket for kline data, not account data).
> 
I mean can I have couple of kline web socket connections open, in different timeframes, in one symbol, with one account API key?
> or may be it's just network packet loss?!
> 
please clarify.

**Comment by hirbod-codes** [comment]
can you be more specific please, you didn't really answer the question, does bingx close websocket connections after a while?

**Comment by bingx-support** [comment]
We don't close user connections. However, we periodically release new features, which may result in disconnections for users. In such cases, you simply need to reconnect.

**Comment by hirbod-codes** [comment]
thank you for the response
